name: dartic
description: A Dart bytecode interpreter.
version: 1.0.0
repository: https://github.com/xudshen/dartic.git

environment:
  sdk: ^3.10.7

dependencies:
  kernel:
    path: vendor/dart-sdk/pkg/kernel

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6