name: darti
description: A Dart bytecode interpreter.
version: 1.0.0
repository: https://github.com/xudshen/darti.git

environment:
  sdk: ^3.10.7

workspace:
  - packages/poc_kernel
  - packages/poc_bench
  - packages/poc_bridge

dependencies:
  kernel:
    path: vendor/dart-sdk/pkg/kernel

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6